name: '🧑🏻‍🔧 Docker Build'
on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 12 AM.
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        VERSION: ['18.04', '20.04', '22.04', '24.04', 'latest']
    steps:
      - name: ➕ Actions - Set up Docker QEMU
        uses: docker/setup-buildx-action@v3

      - name: ➕ Actions - Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ➕ Actions - Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ➕ Actions - Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: wellwelwel/vps:${{ matrix.VERSION }}
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          build-args: VERSION=${{ matrix.VERSION }}
